    -- V1__creating_user_table.sql
    -- Baseado na entidade com @Table(name="tb_users")

    CREATE TABLE IF NOT EXISTS tb_users (
        
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

        -- Colunas NOT NULL
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL
    );