-- V2__creating_post_table.sql
-- Baseado na entidade com @Table(name="tb_posts")

CREATE TABLE IF NOT EXISTS tb_posts (
    
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Colunas de dados
    title VARCHAR(255) NOT NULL,
    content TEXT,

    -- Chave Estrangeira (referencia tb_users)
    user_id BIGINT NOT NULL, 

    -- Restrição de Chave Estrangeira
    CONSTRAINT fk_post_user
        FOREIGN KEY (user_id)
        REFERENCES tb_users (id) 
);